### ISSUE TITLE
how to train the model for the image

### ISSUE THREAD

**Issue by illusioncognitive** [imironica/traffic-signs-keras#1]
Hello, @imironica at first thanks for your work and instructions. I am quite new in machine learning. I have started from [here](https://www.tensorflow.org/hub/tutorials/image_retraining) and it has worked. For your work using which piece of code I can train the image can you please tell me? I have found on that [link](https://github.com/tensorflow/hub/raw/master/examples/image_retraining/retrain.py) that they have prescribed to use `retrain.py` file to train. I want something which you have used to train in your case.

I am sorry if my question is out of the track.

**Comment by imironica** [comment]
Hello @illusioncognitive,

This repo is a dummy example for my students to start creating their own model (from a very stupid one to other more relevant). 

It seems that you want to adapt a Transfer Learning algorithm to your problem.
Maybe you may take a look here (https://github.com/GeorgeSeif/Transfer-Learning-Suite).

Also, it is on my short list to make  a repo with some Transfer Learning techniques.

Regards,
Ionut
